In [1]:
import numpy as np

In [2]:
#creating a 1-d array
a=np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
#creating 2-d array
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
#creating 3-d array
c=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,2,3]]])
c

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [1, 2, 3]]])

In [6]:
#dimension of an array
c.ndim

3

In [7]:
#type of vaiable
type(b)

numpy.ndarray

<h3>Creating an array with exsisting data Converting the array into required data type</h3>


In [8]:
#creating a array with required data type

#syntax:- asarray(input,type, order)
#order for Row Major:-"C", Column major:-"F""

l=[10,20,30]
np.asarray(l,dtype=float)

array([10., 20., 30.])

In [12]:
#converting existing data

# syntax from buffer(buffer, dtype,count,offset)
#count is the length of the returned array
#offset starting position of the returned array
#create an array with given datatype of given length from given position

s= b"welcome"
np.frombuffer(s, dtype="S1", count=-1, offset=0)

array([b'w', b'e', b'l', b'c', b'o', b'm', b'e'], dtype='|S1')

In [13]:
np.frombuffer(s, dtype="S1", count=3, offset=0)

array([b'w', b'e', b'l'], dtype='|S1')

In [16]:
np.frombuffer(s, dtype="S1", count=3, offset=3)

array([b'c', b'o', b'm'], dtype='|S1')

In [18]:
#Syntax:- fromiter(iterable, dtype, count)


t=(10,20,30,40)
s="123654"
np.fromiter(s, dtype="float", count=-1)

array([1., 2., 3., 6., 5., 4.])

<h3>Creating arrays with numerical ranges</h3>

In [21]:
#Syntax:- arange(start, end, step, dtype)
np.arange(0,10,2,dtype=float)

array([0., 2., 4., 6., 8.])

In [31]:
#syntax:- linspace(start, end,num,endpoint,retstep,dtype)

#num= number of required values in array(optional, by default it is 50 values)
#endpoint= TRUE- Stop index will be included
#endpoint= False- Stop index will not be included(optional, by default it is TRUE)
#retstep= Difference between the values
        # True- Step Value is visable
        #False- Step Value is not visable
a=np.linspace(0,10,4,endpoint=True,retstep=True,dtype=int)
a




(array([ 0,  3,  6, 10]), 3.3333333333333335)

In [33]:
#syntax:- logspace(start, end,num,endpoint,base,dtype)
a=np.logspace(0,10,4,endpoint=True,base=2,dtype=int)
a

array([   1,   10,  101, 1024])

<h3> INITIALIZING ARRAYS IN NUMPY ( ZEROS( ) ,ONES( ) ,FULL( ) ,EYE( ) FUNCTIONS ) </h3>

In [37]:
#Shape()---> returns tuple specifying indices and no of elements

a=[[10,20,30],[66,40,50]]
np.shape(a)

(2, 3)

In [39]:
#reshape(array_name, dimen)--> re shapes the array

np.reshape(a,(1,6))

array([[10, 20, 30, 66, 40, 50]])

In [40]:
#Syntax:- zeros(shape,dtype)

np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [41]:
#syntax:- ones(shape, dtype)
#hello

np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [42]:
#syntax:- full(shape,value,dtype)----> fills the entire array with the value specified

np.full((2,5),99)

array([[99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99]])