In [69]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import math

In [3]:
df=pd.read_csv("homeprices.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [6]:
medn=df.bedrooms.median() 

In [10]:
df.bedrooms=df.bedrooms.fillna(medn)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [13]:
reg=linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [14]:
reg.coef_


array([  112.06244194, 23388.88007794, -3231.71790863])

In [15]:
reg.intercept_

221323.00186540443

In [21]:
reg.predict([[3000,4,40]])

array([521797.13165825])

In [22]:
112.06244194*3000+23388.88007794*4-3231.71790863*40+221323.00186540443

521797.1316519644

In [24]:
reg.predict([[2500,4,5]])

array([578876.03748933])

In [63]:
df2=pd.read_csv("hiring.csv")
df2
df2.experience=df2.experience.fillna('zero')
df2

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [54]:
from word2number import w2n

In [64]:
#df2['experience']=[w2n.word_to_num(x) for x in df2.experience]
df2['experience']=df2['experience'].apply(w2n.word_to_num)

df2

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [75]:
df2['test_score(out of 10)']=df2['test_score(out of 10)'].fillna(df2['test_score(out of 10)'].mean())
df2['test_score(out of 10)']=df2['test_score(out of 10)'].apply(math.floor)
df2

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                      8                           9      50000
1           0                      8                           6      45000
2           5                      6                           7      60000
3           2                     10                          10      65000
4           7                      9                           6      70000
5           3                      7                          10      62000
6          10                      7                           7      72000
7          11                      7                           8      80000

In [80]:
reg2=linear_model.LinearRegression()
reg2.fit(df2[['experience','test_score(out of 10)','interview_score(out of 10)']],df2['salary($)'])

LinearRegression()

In [82]:
reg2.predict([[2,9,6]])

array([53713.86677124])

In [83]:
reg2.predict([[12,10,10]])

array([93747.79628651])